### ISSUE TITLE
Crash on 2.3.7

### ISSUE THREAD

**Issue by farwayer** [ghahramani/viewpager#3]
```
[ERROR] :  AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
[ERROR] :  AndroidRuntime:   at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
[ERROR] :  AndroidRuntime:   at com.astuetz.viewpager.extensions.PagerSlidingTabStrip.<init>(PagerSlidingTabStrip.java:162)
[ERROR] :  AndroidRuntime:   at com.astuetz.viewpager.extensions.PagerSlidingTabStrip.<init>(PagerSlidingTabStrip.java:115)
[ERROR] :  AndroidRuntime:   at com.astuetz.viewpager.extensions.PagerSlidingTabStrip.<init>(PagerSlidingTabStrip.java:111)
[ERROR] :  AndroidRuntime:   at com.navid.tabs.PagerTabsView.<init>(PagerTabsView.java:55)
[ERROR] :  AndroidRuntime:   at com.navid.tabs.PagerTabsView.<init>(PagerTabsView.java:86)
[ERROR] :  AndroidRuntime:   at com.navid.tabs.PagerTabsProxy.createView(PagerTabsProxy.java:40)
```

Test app from you version of PagerSlidingTabStrip work fine but not ti module.

**Comment by konstantinbueschel** [comment]
Thanx for your answer! In my project I use this fork, but the bug is also given in this fork
